server:
  port: 8092

  error:
    include-details: always
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3300/invoices
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8096/eureka/
Feign:
  hystrix:
    enabled: true
managment:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
